# Generated by Django 4.2.7 on 2023-12-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='prixavant',
            field=models.FloatField(default=0),
        ),
    ]
